environment:
  matrix:
    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python36-x64"

init:
  - cmd: ver

install:
  - cmd: cd
  - cmd: "%PYTHON%\\python --version"
  - cmd: "%PYTHON%\\python -m pip install .[dev]"

build: off

test_script:
  - cmd: "%PYTHON%\\python -m pytest"
